// Package insults provides an assortment of randomly generated (thanks ChatGPT) insults targeted at software developers
// specifically about their code quality.
package insults

import "math/rand"

// Get returns a random insult, for when you just want to tease a dev.
//
//	insults.Get() // "Your code is the reason debuggers were invented"
func Get() string {
	index := rand.Intn(len(normal))
	return normal[index]
}

// GetWorse returns a more cutting insult, for when you really want to cause pain.
//
//	insults.GetWorse() // "The kindest thing to do to your repo is force push a commit deleting it all"
func GetWorse() string {
	index := rand.Intn(len(worse))
	return worse[index]
}

// normal insults for basic insulting power.
var normal = [...]string{
	"Your code is so bad, it segfaults in the comments.",
	"I'd call your code spaghetti, but that would be an insult to pasta.",
	"Your code looks like you hit the keyboard with your face.",
	"I've seen more readable obituaries.",
	"Even a monkey with a typewriter could write better code.",
	"Your code is like a Windows update—unexpected and disappointing.",
	"Did you mean to write an infinite loop, or is your incompetence just infinite?",
	"Your code is the reason comments were invented.",
	"If bugs were a currency, you'd be a billionaire.",
	"Your code is proof that not everyone should code.",
	"Even AI refuses to debug your code.",
	"Your code is the best argument against copy-pasting from Stack Overflow.",
	"I'd prefer deciphering ancient hieroglyphics over your code.",
	"If your code were a horror movie, it would be banned for being too scary.",
	"Your code runs as well as a snail in quicksand.",
	"If bad code were a crime, you'd be on death row.",
	"Even your code's syntax errors have syntax errors.",
	"Your code is the reason the undo button exists.",
	"If there was an award for the worst code, you'd win it every year.",
	"Your code is like a black hole; it sucks everything into it and nothing useful comes out.",
	"I didn't know it was possible to write code that ugly.",
	"Your code makes Internet Explorer look like a modern browser.",
	"Reading your code is like watching paint dry—painfully slow and dull.",
	"Your code has more bugs than a cheap motel.",
	"The only pattern in your code is the lack of any pattern.",
	"Your code should come with a health warning.",
	"Your variable names are as meaningful as random numbers.",
	"Your code is so slow, it would lose a race to a glacier.",
	"You write code like you're getting paid by the bug.",
	"If your code were a car, it would be a Yugo.",
	"Your code is a prime example of why code reviews are necessary.",
	"You must have learned to code from a cereal box.",
	"Your code is a great case study for why we need better coding education.",
	"I've seen toddlers build better structures with LEGO.",
	"Debugging your code is like playing whack-a-mole with no hammer.",
	"Your code is the reason compilers cry.",
	"If procrastination wrote code, it would look like yours.",
	"Your code is the Bermuda Triangle of logic.",
	"Even a random number generator produces more predictable results than your code.",
	"Your code is the digital equivalent of a landfill.",
	"If your code were art, it would be abstract in the worst way.",
	"Your code should come with a search party.",
	"Your code is so convoluted, even a maze has an easier exit.",
	"Every line of your code is a new adventure in pain.",
	"Your code is like a bad joke: hard to understand and not funny.",
	"The only thing your code is good at is crashing.",
	"Your code makes QuickSort look like O(n^2).",
	"Your code is like a minefield: one wrong step and everything blows up.",
	"If your code were a building, it would have collapsed by now.",
	"Reading your code should count as a form of torture.",
	"Your code is the reason my hair is turning gray.",
	"Your code runs slower than my grandma, and she's been dead for ten years.",
	"Your functions have more side effects than a pharmacy.",
	"Your codebase is a monument to poor decisions.",
	"I've seen better indentation in a book of poetry.",
	"Your code is the software equivalent of a Rube Goldberg machine.",
	"If there were a PhD in writing bad code, you'd be the first graduate.",
	"Your code is a shining example of how not to code.",
	"Even a blindfolded chimp could refactor your code better.",
	"Your code should be buried and forgotten.",
	"Reading your code is like solving a Rubik's cube with missing pieces.",
	"Your code is the reason we have backups.",
	"Your code is a perfect storm of bad practices.",
	"I've seen better structure in a house of cards.",
	"Your code makes a labyrinth look straightforward.",
	"If your code were a recipe, it would be for disaster.",
	"Your code is a masterclass in what not to do.",
	"Even your bugs have bugs.",
	"Your code has more holes than Swiss cheese.",
	"I've seen fewer tangles in a box of Christmas lights.",
	"Your code is a dictionary definition of technical debt.",
	"Your code is so ugly, it makes a train wreck look beautiful.",
	"Your code should come with a “Do Not Disturb” sign.",
	"Reading your code is like deciphering an alien language.",
	"Your codebase is a monument to bad design.",
	"Your code is like a haunted house: scary and full of surprises.",
	"Your code is the reason some people fear technology.",
	"Your code is like a broken GPS: it never leads to the right place.",
	"Your code is so bad, even git doesn't want to commit it.",
	"Your code is an insult to bits and bytes everywhere.",
	"If there were a museum of bad code, your work would be the main exhibit.",
	"Your code makes the blue screen of death look inviting.",
	"Your code could be used as a case study for failure.",
	"Your code has more dead ends than a corn maze.",
	"Your code is the reason exceptions exist.",
	"If your code were an animal, it would be a platypus: confusing and weird.",
	"Your code should be quarantined for public safety.",
	"Your code is a perfect example of why code reviews are painful.",
	"Your code is so disorganized, even Marie Kondo couldn't help it.",
	"Your code is a prime example of entropy.",
	"If your code were a story, it would be a tragedy.",
	"Your code is like a horror novel: full of unexpected terrors.",
	"Your code is so bad, even your IDE refuses to format it.",
	"If your code were a joke, it wouldn't be funny.",
	"Your code makes the Titanic look unsinkable.",
	"Your code is the digital equivalent of a train wreck.",
	"Even spaghetti code looks organized compared to yours.",
	"Your code is a disaster waiting to happen.",
	"Reading your code is like walking through a minefield.",
	"Your code is a shining beacon of what not to do.",
}

// worse insults, for more powerful insulting.
var worse = [...]string{
	"Your code is a crime against computing.",
	"The only thing worse than your code is your complete lack of shame.",
	"If stupidity were code, yours would be a masterpiece.",
	"Your code should be arrested for public indecency.",
	"The best feature of your code is the delete button.",
	"Your code is the reason people still use pen and paper.",
	"Even your computer is embarrassed to run your code.",
	"Your code is so bad, it made the compiler cry.",
	"If I wanted to torture someone, I'd make them read your code.",
	"Your code could turn a supercomputer into a doorstop.",
	"Your code is a great way to ruin a good application.",
	"The only thing your code successfully does is fail.",
	"Your code is proof that not all progress is good.",
	"If your code were a ship, it would sink before it left the dock.",
	"Your code is the reason aliens don't visit us.",
	"The best part of your code is the part you didn't write.",
	"Your codebase is a dumpster fire in a hurricane.",
	"Your code is so bad, it should come with a refund.",
	"The only legacy your code will leave is a warning to others.",
	"Your code is so slow, it should come with a calendar.",
	"Your code has more bugs than a termite mound.",
	"If your code were a movie, it would go straight to VHS.",
	"Your code is like a bad tattoo: permanent and regrettable.",
	"Your code is the reason “Ctrl+Z” exists.",
	"Reading your code is like stepping into a nightmare.",
	"Your code is an insult to programming languages.",
	"Even malware is better written than your code.",
	"Your code is a masterclass in failure.",
	"If your code were a building, it would violate every safety code.",
	"Your code is like quicksand: the more you interact with it, the worse it gets.",
	"Your code is the definition of technical debt.",
	"The only thing your code does efficiently is waste time.",
	"Your code is a great example of why some people should never code.",
	"Your code could serve as a horror story for aspiring developers.",
	"Your code is a testament to bad decisions.",
	"Your code makes a garbage collector want to quit.",
	"Your codebase is a breeding ground for bugs.",
	"Even chaos theory can't explain your code.",
	"Your code is a black hole of productivity.",
	"Your code is like a bad smell: it lingers long after you're gone.",
	"The only good part of your code is the part that isn't written yet.",
	"Your code is so bad, it should come with a warning label.",
	"Your code is a liability.",
	"If your code were a disease, it would be terminal.",
	"Your code is a perfect example of what happens when you don't care.",
	"Your code is a plague on the software industry.",
	"If your code were a meal, it would give everyone food poisoning.",
	"Your code is the digital equivalent of toxic waste.",
	"Your code is a dark abyss from which nothing good can emerge.",
	"Your code is so bad, it should be quarantined.",
	"Your code is the worst kind of pollution.",
	"Even a drunkard with a keyboard would produce better code.",
	"Your code makes the internet a worse place.",
	"Your code is an insult to electrons.",
	"Your code is the definition of incompetence.",
	"Your code is the reason people fear technology.",
	"If your code were a product, it would be recalled.",
	"Your code is like a dead fish: it stinks and it's hard to get rid of.",
	"Your code is a testament to laziness.",
	"Your code is so bad, it should be incinerated.",
	"Your code is a monument to mediocrity.",
	"Your code is a disaster wrapped in a catastrophe.",
	"If your code were a person, it would be in prison.",
	"Your code is a blight on the digital landscape.",
	"Your code is an exercise in futility.",
	"Your code is so bad, it defies description.",
	"Your code is a train wreck that never stops crashing.",
	"If your code were a joke, no one would laugh.",
	"Your code is the epitome of failure.",
	"Your code is a wasteland of poor decisions.",
	"Your code is a cautionary tale.",
	"If your code were a drink, it would be poison.",
	"Your code is a stain on the software community.",
	"Your code is a perfect storm of bad practices.",
	"Your code should be buried and never spoken of again.",
	"Your code is an affront to good coding standards.",
	"Your code is a minefield of errors.",
	"Your code is a case study in how not to code.",
	"Your code is a monument to ignorance.",
	"Your code is so bad, even a syntax highlighter cries.",
	"Your code is a masterclass in how to do everything wrong.",
	"Your code is an abomination.",
	"Your code is a nightmare wrapped in a disaster.",
	"Your code is a perfect example of failure.",
	"Your code is an insult to logic.",
	"Your code is a wasteland of broken dreams.",
	"Your code is the digital equivalent of a dumpster fire.",
	"Your code is the reason people hate programming.",
	"Your code is a disgrace to the profession.",
	"Your code is a perfect example of why standards exist.",
	"Your code is an ocean of errors.",
	"Your code is a black mark on your resume.",
	"Your code is the epitome of bad practices.",
	"Your code is a horror show.",
	"Your code is a testament to incompetence.",
	"Your code is a cesspool of bad decisions.",
	"Your code is an affront to anyone who loves coding.",
	"Your code is a disaster waiting to happen.",
	"Your code is the reason code reviews are painful.",
	"Your code is a travesty.",
}
