version: 2

project_name: git-rekt

before:
  hooks:
    - go mod tidy

builds:
  - id: git-rekt
    dir: "."
    main: "./cmd/git-rekt"
    binary: git-rekt
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X go.followtheprocess.codes/git-rekt/internal/cli.version={{.Version}}
      - -X go.followtheprocess.codes/git-rekt/internal/cli.commit={{.Commit}}
      - -X go.followtheprocess.codes/git-rekt/internal/cli.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"

homebrew_casks:
  - name: git-rekt
    binary: git-rekt
    directory: Casks
    description: A profoundly unhelpful git extension
    homepage: https://github.com/FollowTheProcess/git-rekt
    conflicts:
      - formula: git-rekt
    commit_author:
      name: Tom Fleet
      email: me@followtheprocess.codes
    repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-rekt"]
          end

archives:
  - id: git-rekt
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: git-rekt
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version }}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  disable: true
