version: 2

project_name: git-rekt

before:
  hooks:
    - go mod tidy

builds:
  - id: git-rekt
    dir: "."
    main: "./cmd/git-rekt"
    binary: git-rekt
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/FollowTheProcess/git-rekt/internal/cli.version={{.Version}}
      - -X github.com/FollowTheProcess/git-rekt/internal/cli.commit={{.Commit}}
      - -X github.com/FollowTheProcess/git-rekt/internal/cli.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"

brews:
  - repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    goarm: "7"
    directory: Formula
    commit_author:
      name: Tom Fleet
      email: tomfleet2018@gmail.com
    homepage: https://github.com/FollowTheProcess/git-rekt
    description: A profoundly unhelpful git extension
    license: MIT License
    install: |
      bin.install "git-rekt"
    test: |
      "#{bin}/git-rekt --version"

archives:
  - id: git-rekt
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: git-rekt
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version }}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  disable: true
